AWSTemplateFormatVersion: 2010-09-09

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the sample Amazon S3 bucket with a lifecycle configuration.
  BucketDomain:
    Value: !Join 
      - "//"
      - - "https:"
        - !GetAtt S3Bucket.DomainName
    Description: Domain name of the bucket